FROM seal-python

# define the folder where our src should exist/ be deposited
ARG SRC=/server
RUN mkdir -p ${SRC}

# copy into container requirements and install them before rest of code
COPY ./requirements.txt ${SRC}/.
RUN pip3 install -r ${SRC}/requirements.txt

COPY ./server.py ${SRC}/.
COPY ./run_server.sh ${SRC}/.
RUN chmod +x ${SRC}/run_server.sh
