version: '3'
services:
  seal-python:
    build: ./seal-python
    image: seal-python
  l-infinity-datagen:
    build: ./datagen
    volumes:
      - ./data:/data:rw
      - ./Challenge:/Challenge:ro
    user: "${UID}:${GID}"
    depends_on:
      - seal-python
